stage:
  deploy:
    CRON_CONSUMERS_RUNNER:
        cron_run: true
        max_messages: 1000
        consumers: []
    MYSQL_USE_SLAVE_CONNECTION: true
    REDIS_BACKEND: '\Magento\Framework\Cache\Backend\RemoteSynchronizedCache'
    REDIS_USE_SLAVE_CONNECTION: true
