<?php

// @codingStandardsIgnoreFile
use Ecommerce121\SearchSpring\Model\Store\Config;
use Magento\Framework\App\ObjectManager;

/**
 * @var $searchSpring Config
 */
$objectManager = ObjectManager::getInstance();
$searchSpring = $objectManager->get(Config::class);

$isSearchSpringAllowed = $searchSpring->isSearchSpringAllowed();

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php if ($isSearchSpringAllowed) : ?>
<div id="searchspring-sidebar"></div>
<div id="searchspring-content">
<?php endif; ?>

    <?php
        $_productCollection = $block->getLoadedProductCollection();
        $_helper = $this->helper('Magento\Catalog\Helper\Output');
    ?>
    <?php if (!$_productCollection->count()): ?>
        <div class="message info empty"><div><?php echo /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
    <?php else: ?>
        <?php
            if ($block->getMode() == 'grid') {
                $viewMode = 'grid';
                $image = 'category_page_grid';
                $showDescription = false;
                $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            } else {
                $viewMode = 'list';
                $image = 'category_page_list';
                $showDescription = true;
                $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
            }

            /**
             * Position for actions regarding image size changing in vde if needed
             */
            $pos = $block->getPositioned();
        ?>
            <?php if ($isSearchSpringAllowed) : ?>
                <div class="toolbar toolbar-products">
                    <?php echo $block->getToolbarHtml() ?>
                    <?php echo $block->getAdditionalHtml() ?>
                </div>
            <?php else: ?>
                <?php echo $block->getToolbarHtml() ?>
                <?php echo $block->getAdditionalHtml() ?>
            <?php endif; ?>
            <div class="products wrapper <?php echo /* @escapeNotVerified */ $viewMode ?> products-<?php echo /* @escapeNotVerified */ $viewMode ?>">
                <?php $iterator = 1; ?>
                <ol class="products list items product-items productos-basket">
                    <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                    <?php foreach ($_productCollection as $_product): ?>
                    <?php echo /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                    <?php if($_product->getTypeId() == 'basket'): ?>
                    <div class="product-item-info basket-product" data-container="product-<?php echo /* @escapeNotVerified */ $viewMode ?>">
                        <?php else: ?>
                        <div class="product-item-info" data-container="product-<?php echo /* @escapeNotVerified */ $viewMode ?>">
                            <?php endif; ?>
                            <?php
                            $productImage = $block->getImage($_product, $image, ['loading' => null]);
                            if ($pos != null) {
                                $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;"';
                            }
                            ?>
                            <div class="product-holder">
                                <?php // Product Image ?>
                                <a href="<?php echo /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                    <?php echo $productImage->toHtml() ?>
                                </a>
                                <div class="product details product-item-details">
                                    <?php
                                    $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                    ?>
                                    <strong class="product name product-item-name">
                                        <a class="product-item-link"
                                           href="<?php echo /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                            <?php echo /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                        </a>
                                    </strong>

                                    <div class="product sku product-item-sku">
                                        <?php echo /* @escapeNotVerified */ $_product->getSku() ?>
                                    </div>

                                    <div class="product short-description product-item-short-description">
                                        <?php /* @escapeNotVerified */
                                        echo $_helper->productAttribute(
                                            $_product,
                                            $_product->getAfeGlobalFitmentSummary(),
                                            'afe_global_fitment_summary'
                                        ) ?>
                                    </div>
                                    <?php
                                    if ($_product->getPriceType() == 1) {
                                        echo /* @escapeNotVerified */ $block->getProductPrice($_product);
                                    }
                                    ?>
                                    <?php if($_product->getTypeId() !== 'basket'): ?>
                                        <?php echo /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                                        <?php echo $block->getProductDetailsHtml($_product) ?>
                                    <?php endif; ?>

                                    <?php if($_product->getTypeId() == 'basket'): ?>
                                        <div class="product-basket-price"></div>
                                    <?php endif; ?>

                                    <?php
                                    /**
                                     * @var $block \Ecommerce121\ProductVariation\Block\Product\View\Type\SimpleVariation
                                     */
                                    $blockVariation = $this->getLayout()->getBlock('ecommerce121.product.variation.category.page');
                                    ?>
                                    <?php if ($blockVariation && $blockVariation->isProductVariation($_product)) : ?>
                                        <div class="product-variation-container-list">
                                            <?php $variations = $blockVariation->getProductsVariations($_product); ?>
                                            <?php if (count($variations) < 5) : ?>
                                                <label class="product-variation-label"
                                                       title="<?= $block->escapeHtml($_product->getSkuOption()); ?>">
                                                    <?= $block->escapeHtml(__('Option:')) ?>
                                                    <span><?= $block->escapeHtml($_product->getSkuOption()) ?></span>
                                                </label>
                                                <div class="product-variation-list">
                                                    <?php
                                                    foreach ($variations as $product) : ?>
                                                        <div class="product-variation-item">
                                                            <a href="<?= $block->escapeUrl($block->getProductUrl($product)); ?>"
                                                               class="product photo product-item-photo" title="<?= $product->getSkuOption(); ?>">
                                                                <?= $block->getImage($product, 'product_base_image')->toHtml(); ?>
                                                            </a>
                                                            <?= $block->getProductPrice($product) ?>
                                                        </div>
                                                    <?php endforeach; ?>
                                                </div>
                                            <?php else: ?>
                                                <label for="ecommerce-options"><?= $block->escapeHtml(__('Select Option:')) ?></label>

                                                <select name="ecommerce_options" id="ecommerce-options">
                                                    <?php foreach ($variations as $variation) : ?>
                                                        <option value="<?= $block->escapeHtml($variation->getSkuOption()) ?>"
                                                                data-url="<?= $block->escapeUrl($block->getProductUrl($variation)); ?>">
                                                            <?= $block->escapeHtml($variation->getSkuOption()) ?>
                                                        </option>
                                                    <?php endforeach; ?>
                                                </select>
                                            <?php endif; ?>
                                            <script type="text/x-magento-init">
                                                {
                                                    ".product-variation-container-list": {
                                                        "product_variation": {}
                                                    }
                                                }
                                            </script>
                                        </div>
                                    <?php endif; ?>

                                    <div class="product-item-inner">
                                        <?php if ($showDescription):?>
                                            <div class="product description product-item-description">
                                                <?php echo /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getAfeGlobalFitmentSummary(), 'afe_global_fitment_summary') ?>
                                                <a href="<?php echo /* @escapeNotVerified */ $_product->getProductUrl() ?>" title="<?php echo /* @escapeNotVerified */ $_productNameStripped ?>"
                                                   class="action more"><?php echo /* @escapeNotVerified */ __('Learn More') ?></a>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                            <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                    <a href="<?php echo /* @escapeNotVerified */ $_product->getProductUrl() ?>" type="submit"
                                       title="<?php echo $block->escapeHtml(__('More Info')) ?>"
                                       class="action primary">
                                        <span><?php echo /* @escapeNotVerified */ __('More Info >') ?></span>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <?php echo ($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
                        <?php endforeach; ?>
                </ol>
            </div>
            <?php echo $block->getToolbarHtml() ?>
            <?php if (!$block->isRedirectToCartEnabled()) : ?>
                <script type="text/x-magento-init">
                {
                    "[data-role=tocart-form], .form.map.checkout": {
                        "catalogAddToCart": {
                            "product_sku": "<?php echo /* @NoEscape */ $_product->getSku() ?>"
                        }
                    },
                    ".product-items" : {
                        "Magento_Catalog/js/grids": {
                            "items": ".page-products .product-items .product-holder"
                        }
                    }
                }
                </script>
            <?php endif; ?>
        </div>
    <?php endif; ?>

<?php if ($isSearchSpringAllowed) : ?>
</div>
<?php endif; ?>
