<?php
// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
/* @var WeltPixel\OwlCarouselSlider\Helper\Products $helper */
$helper = $this->helper('WeltPixel\OwlCarouselSlider\Helper\Products');
$sliderConfiguration = $helper->getSliderConfiguration($block->getType());
$sliderConfig = json_encode($sliderConfiguration);
$helperCustom = $this->helper('WeltPixel\OwlCarouselSlider\Helper\Custom');
$breakpointConfiguration = $helperCustom->getBreakpointConfiguration();
$displaySocial = $helperCustom->getDisplaySocial();
$breakpoint   = $breakpointConfiguration;
$enableSlider = (array_key_exists('status', $sliderConfiguration) && $sliderConfiguration['status'] == 1) ? true : false;
$imageCreationOptions = [];
$slidesCount = 5;
if ($enableSlider) {
    $imageCreationOptions['weltpixel_owlcarousel'] = true;
    if ($sliderConfiguration['lazyLoad']) {
        $imageCreationOptions['weltpixel_lazyLoad'] = true;
    }
}
$slideBy = 1;
$_typeBClass = '';
$_isTypeB = false;
$_product = $block->getProduct();
if ($_product->getPageLayout() === 'product-type-b') {
    $_typeBClass = 'related-type-b';
    $_isTypeB = true;
};

?>
<?php
switch ($type = $block->getType()) {
    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = ($enableSlider && $sliderConfiguration['title']) ? $sliderConfiguration['title'] : __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();
            $slideBy = $sliderConfiguration['slide_by'];
            $showWishlist = $displaySocial['display_wishlist'];
            $showCompare = $displaySocial['display_compare'];
            $showCart = true;
            $templateType = null;
            $description = false;
        }
        break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = ($enableSlider && $sliderConfiguration['title']) ? $sliderConfiguration['title'] : __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();
            $slideBy = $sliderConfiguration['slide_by'];
            $showWishlist = $displaySocial['display_wishlist'];
            $showCompare = $displaySocial['display_compare'];
            $showCart = true;
            $templateType = null;
            $description = false;
        }
        break;
    case 'other':
        break;
}

?>

<?php if ($exist) : ?>

    <div class="block-product-carousel-wrapper block-product-carousel-wrapper--related <?= $_isTypeB?'block-product-carousel-wrapper--type-b':''?>">
        <div class="block-product-carousel <?= $type ?> block-margin block <?php /* @escapeNotVerified */ echo $class . !$enableSlider ? ' row' : ''; ?>" id="<?= $type ?>-products" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
            <div class="collapsible-block" data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": true }}'>
                <h3 class="block-title title" role="heading" data-role="title">
                    <span id="block-<?php /* @escapeNotVerified */ echo $class ?>-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></span>
                </h3>
                <div class="block-content content" role="content" data-role="content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class ?>-heading">
                    <div class="products wrapper grid products-grid <?php if(count($items) < $slidesCount) { echo $block->escapeHtml(__('disabled-arrows'));} ?> products-<?php /* @escapeNotVerified */ echo $type; ?>">
                        <ol class="products list items product-items<?php echo $enableSlider ? ' owl-carousel-products-' . $type : ''; ?>">
                            <?php $product_item = $enableSlider ? '' : ' product-item'; ?>
                            <?php $iterator = 1; ?>
                            <?php foreach ($items as $_item) : ?>
                                <?php $available = ''; ?>
                                <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related') : ?>
                                    <?php if (!$_item->getRequiredOptions()) : ?>
                                        <?php $available = 'related-available'; ?>
                                    <?php endif; ?>
                                <?php endif; ?>
                                <?php /* @escapeNotVerified */ echo ($iterator++ == 1) ? '<li class="item product product-item" style="">' : '</li><li class="item product product-item" style="">' ?>
                                <div class="product-item-info <?php /* @escapeNotVerified */ echo $available; ?>">
                                    <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
                                    <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                                        <?php echo $block->getImage($_item, $image, $imageCreationOptions)->toHtml(); ?>
                                    </a>
                                    <div class="product details product-item-details">
                                        <div class="info">
                                            <strong class="product name product-item-name">
                                                <a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                                                    <?php echo $block->escapeHtml($_item->getName()) ?>
                                                </a>
                                            </strong>
                                            <?php if(!$_isTypeB): ?>
                                                <span class="sku"><?= $_item->getSku(); ?></span>
                                                <span class="short-description"><?= $_item->getAfeGlobalFitmentSummary(); ?></span>
                                            <?php endif;?>
                                            <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>

                                            <?php if ($templateType) : ?>
                                                <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                            <?php endif; ?>
                                        </div>
                                        <?php if ($showWishlist || $showCompare || $showCart) : ?>
                                            <div class="product actions product-item-actions">
                                                <?php if ($showCart) : ?>
                                                    <div class="actions-primary">
                                                        <?php if ($_item->isSaleable()) : ?>
                                                            <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)) : ?>
                                                                <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                                </button>
                                                            <?php else : ?>
                                                                <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                                $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                                ?>
                                                                <button class="action tocart primary" data-post='<?php /* @escapeNotVerified */ echo $postData; ?>' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                                </button>
                                                            <?php endif; ?>
                                                        <?php else : ?>
                                                            <?php if ($_item->getIsSalable()) : ?>
                                                                <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                            <?php else : ?>
                                                                <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                            <?php endif; ?>
                                                        <?php endif; ?>
                                                        <?php if($_isTypeB): ?>
                                                            <button class="action more-info">
                                                                <a title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"><?php /* @escapeNotVerified */ echo __('More info') ?></a>
                                                            </button>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>

                                                <?php if ($showWishlist || $showCompare) : ?>
                                                    <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist) : ?>
                                                            <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>' class="action towishlist" data-action="add-to-wishlist" title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                                <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                            </a>
                                                        <?php endif; ?>
                                                        <?php if ($block->getAddToCompareUrl() && $showCompare) : ?>
                                                            <?php
                                                            $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                                            ?>
                                                            <a href="#" class="action tocompare" data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item); ?>' data-role="add-to-links" title="<?php /* @escapeNotVerified */ echo __('Add to Compare'); ?>">
                                                                <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                                            </a>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                                <?php echo ($iterator == count($items) + 1) ? '</li>' : '' ?>
                            <?php endforeach ?>
                        </ol>
                        <?php if ($enableSlider) : ?>
                            <div id="pre-div">
                                <?php $loaderHelper = $this->helper('WeltPixel\OwlCarouselSlider\Helper\ImageLoader'); ?>
                                <?php if ($loaderHelper->useDefaultLoader()) : ?>
                                    <div class="cssload-loader">
                                        <div class="cssload-inner cssload-one"></div>
                                        <div class="cssload-inner cssload-two"></div>
                                        <div class="cssload-inner cssload-three"></div>
                                    </div>
                                <?php else : ?>
                                    <table class="imageloader-loader">
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <img src="<?= $loaderHelper->getLoadingImageUrl() ?>" />
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                <?php endif; ?>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php if ($enableSlider) : ?>
        <script>
            require(['jquery', 'owl_carousel', 'owl_config'],
                function($) {
                    $(document).ready(function() {
                        var products_type = '<?php echo $type; ?>',
                            slider_config = <?php echo $sliderConfig; ?>,

                            carouselElement = $('.owl-carousel-products-' + products_type),
                            windowWidth = $(window).width(),
                            carouselWidth = carouselElement.width(),
                            carouselContainer = carouselWidth + 120,

                            items = ((slider_config.items >= 0 && slider_config.items != null) ? slider_config.items : 2),

                            stagePadding = slider_config.stagePadding != '' ? parseInt(slider_config.stagePadding) : 0,

                            sPBrk_1 = slider_config.stagePadding_brk1 != '' ? parseInt(slider_config.stagePadding_brk1) : 0,
                            sPBrk_2 = slider_config.stagePadding_brk2 != '' ? parseInt(slider_config.stagePadding_brk2) : 0,
                            sPBrk_3 = slider_config.stagePadding_brk3 != '' ? parseInt(slider_config.stagePadding_brk3) : 0,
                            sPBrk_4 = slider_config.stagePadding_brk4 != '' ? parseInt(slider_config.stagePadding_brk4) : 0;

                        /** Lazyload bug when fewer items exist in the carousel then the ones displayed */
                        carouselElement.on('initialized.owl.carousel', function(event) {
                            var scopeSize = event.page.size,
                                navBtnL = carouselElement.find('.owl-prev'),
                                navBtnR = carouselElement.find('.owl-next');
                            if (event.item.count < event.page.size) {
                                navBtnL.css('display', 'none');
                                navBtnR.css('display', 'none');
                            }

                            for (var i = 0; i < scopeSize; i++) {
                                var imgsrc = $(event.target).find('.owl-item').eq(i).find('img').attr('data-src');
                                $(event.target).find('.owl-item').eq(i).find('img').attr('src', imgsrc);
                                $(event.target).find('.owl-item').eq(i).find('img').attr('style', 'opacity: 1;');
                            }
                        });
                        carouselElement.owlCarousel({
                                center: false,
                                loop: parseInt(slider_config.loop) == 1 ? true : false,
                                lazyLoad: parseInt(slider_config.lazyLoad) == 1 ? true : false,
                                autoplay: parseInt(slider_config.autoplay) == 1 ? true : false,
                                autoplayTimeout: (slider_config.autoplayTimeout > 0 && slider_config.autoplayTimeout != null) ? parseInt(slider_config.autoplayTimeout) : 3000,
                                autoplayHoverPause: parseInt(slider_config.autoplayHoverPause) == 1 ? true : false,
                                slideBy: '<?php echo $slideBy ?>',
                            <?php if($_isTypeB): ?>
                                nav: true,
                                dots: true,
                                items: 2,
                                margin: 30,
                                autoHeight: true,
                            <?php else: ?>
                                nav: false,
                                dots: false,
                                items: 2,
                                margin: 30,
                                autoHeight: false,
                            <?php endif; ?>

                            responsive: {
                                0: {
                                    <?php if($_isTypeB): ?>
                                    nav: true,
                                    dots: true,
                                    items: 2,
                                    <?php else: ?>
                                    nav: true,
                                    dots: false,
                                    items: 2
                                    <?php endif; ?>
                                },
                                560: {
                                    <?php if($_isTypeB): ?>
                                        nav: true,
                                        dots: true,
                                        items: 2,
                                    <?php else: ?>
                                        nav: true,
                                        dots: false,
                                        items: 3
                                    <?php endif; ?>
                                },
                                768: {
                                    <?php if($_isTypeB): ?>
                                        nav: true,
                                        dots: true,
                                        items: 3,
                                    <?php else: ?>
                                        nav: false,
                                        dots: false,
                                        items: 4
                                    <?php endif; ?>
                                },
                                1024: {
                                    <?php if($_isTypeB): ?>
                                        nav: true,
                                        dots: true,
                                        items: 4,
                                    <?php else: ?>
                                        nav: false,
                                        dots: false,
                                        items: 4
                                    <?php endif; ?>
                                },
                                1280: {
                                    <?php if($_isTypeB): ?>
                                        nav: true,
                                        dots: true,
                                        items: 5,
                                        margin: 39,
                                    <?php else: ?>
                                        nav: false,
                                        dots: false,
                                        items: 4,
                                    <?php endif; ?>
                                }
                            }
                        });

                        var carouselControls = carouselElement.find('.owl-nav');
                        if (carouselContainer >= windowWidth) {
                            carouselControls.find('.owl-prev').css({
                                'left': 0,
                                'top': -15
                            });
                            carouselControls.find('.owl-next').css({
                                'right': 0,
                                'top': -15
                            });
                        }

                        carouselElement.on('initialized.owl.carousel changed.owl.carousel', function(event) {
                            navBtnL = carouselElement.find('.owl-prev'),
                            navBtnR = carouselElement.find('.owl-next');
                            if (event.item.count < event.page.size) {
                                navBtnL.css('display', 'none');
                                navBtnR.css('display', 'none');
                            }
                        });

                    });
                });
        </script>
    <?php endif; ?>
    <script>
        require(['jquery'], function($) {

            //  initialized
            var collapsible = $('.collapsible-block');
            if (collapsible.length > 0) {
                collapsible.on('initialized.owl.carousel', function() {
                    if ($(this).hasClass('active')) {
                        $(this).collapsible("deactivate");
                    }
                })
            }
        });
    </script>
<?php endif; ?>
