<?php
/**
 * @var $block \Ecommerce121\ProductVariation\Block\Product\ProductList\RelatedVariation
 */
?>

<?php
$parentProduct = $block->getParentProduct();
$variations = $block->getProductsVariations();
$imageType = 'product_thumbnail_image';
$productType = $block->getParentBlock()->getType();
?>

<?php
$j = 0;
foreach ($variations as $product): ?>
    <div class="<?= /** @var $escaper */ $escaper->escapeHtml($productType)?>-variation-item"
         id="<?= $escaper->escapeHtml($product->getId()) ?>" <?= $j > 0 ? 'style="display: none"' : ''; ?>>
        <div class="product-image">
            <a href="<?= $block->escapeUrl($block->getProductUrl($product)); ?>"
               class="product photo product-item-photo" title="<?= $escaper->escapeHtml($product->getSkuOption()); ?>">
                <?= $block->getImage($product, $imageType)->toHtml() ?>
            </a>
        </div>
        <div class="product details product-item-details">
            <strong class="product name product-item-name">
                <a class="product-item-link"
                   title="<?=  $escaper->escapeHtmlAttr($product->getName()) ?>"
                   href="<?= $escaper->escapeUrl($block->getProductUrl($product)) ?>">
                    <?= $escaper->escapeHtml($product->getName()) ?></a>
            </strong>
            <?= /* @noEscape */ $block->getProductPrice($product) ?>
        </div>
    </div>
    <?php $j++; ?>
<?php endforeach; ?>

<div class="toggle-nav">
    <?php $i = 0 ; ?>
    <?php foreach ($variations as $product): ?>
        <?php $skuOption = $product->getSkuOption(); ?>
        <a  class="<?= /** @var $escaper */ $escaper->escapeHtml($productType)?>-toggle-variation
            <?= $i < 1 ? ' current' : ''; ?>"
            data-target="#<?= $escaper->escapeHtmlAttr($product->getId()) ?>"
            href="#"
            title="<?= $escaper->escapeHtmlAttr($product->getName()) ?>"
            data-sku-option="<?= $escaper->escapeHtml($product->getSkuOption()) ?>">
            <?= $skuOption ? $escaper->escapeHtml($skuOption) : $escaper->escapeHtml($product->getName()) ?>
        </a> <?= $i < count($variations) -1  ? '|' : ''; ?>
        <?php $i++; ?>
    <?php endforeach; ?>
</div>

<script>
    require([
        'jquery'
    ], function ($) {
        $(document).ready(function () {
            $('.<?= /** @var $escaper */ $escaper->escapeHtml($productType)?>-toggle-variation').click(function(e){
                var target = $(this).data('target'),
                    parent = $(this).parent().parent(),
                    checkId = target.replace('#','');

                parent.find('.<?= /** @var $escaper */ $escaper->escapeHtml($productType)?>-toggle-variation')
                    .removeClass('current')
                $(this).addClass('current');

                // replace checkbox value with variant product id
                parent.find('.extras').find('.extras').val(checkId);
                //display selected product
                $(parent).find('.<?= /** @var $escaper */ $escaper->escapeHtml($productType)?>-variation-item').hide();
                $(parent).find(target).show();

                e.preventDefault();
            });
        });
    });
</script>
