<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View
 */
?>
<div class="collapsible-block block-extras"  data-mage-init='{"collapsible":{"collapsible": true, "active": false }}'>
    <h3 class="block-title title" role="heading"  data-role="title">
        <span id="block-extras block-extras-heading" role="heading" aria-level="2"><?= __('EXTRAS') ?></span>
    </h3>
    <div class="block-content content" data-mage-init='{"extrasProducts":{"extrasCheckbox":".extras.checkbox"}}' data-role="content" aria-labelledby="block-extras-heading">
            <form action="<?= $block->getUrl('extras/cart/add') ?>" method="post" class="extra-cart-form" id="product_addtocart_form">
                <input type="hidden" name="extras_product" id="extras-products-field" value="" />
                <input type="hidden" value="<?php echo $block->getFormKey(); ?>" name="form_key" />
                <input type="hidden" value="<?php echo $block->getProduct()->getId(); ?>" name="product" />
                <?= $block->getChildHtml('') ?>
                <div class="bundle-add-to-cart">
                    <button disabled id="extras-products-add-to-cart" type="submit" title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>" class="action">
                        <span class="bundle-button"><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                    </button>
                </div>
            </form>
    </div>
</div>
