<?php
/**
 * Product media data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Gallery
 */
?>

<?php
$images = $block->getGalleryImages()->getItems();
$mainImage = current(array_filter($images, function ($img) use ($block) {
    return $block->isMainImage($img);
}));

if (!empty($images) && empty($mainImage)) {
    $mainImage = $block->getGalleryImages()->getFirstItem();
}

$helper = $block->getData('imageHelper');
$mainImageData = $mainImage ?
    $mainImage->getData('medium_image_url') :
    $helper->getDefaultPlaceholderUrl('image');

?>

<div class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-placeholder">
    <img
        alt="main product photo"
        class="gallery-placeholder__image"
        src="<?= /* @noEscape */ $mainImageData ?>"
    />
</div>

<script type="text/x-magento-init">
    {
        "[data-gallery-role=gallery-placeholder]": {
            "mage/gallery/gallery": {
                "mixins":["magnifier/magnify"],
                "magnifierOpts": <?= /* @noEscape */ $block->getMagnifier() ?>,
                "data": <?= /* @noEscape */ $block->getGalleryImagesJson() ?>,
                "options": <?= /* @noEscape */ $block->getGalleryOptions()->getOptionsJson() ?>,
                "fullscreen": <?= /* @noEscape */ $block->getGalleryOptions()->getFSOptionsJson() ?>,
                 "breakpoints": <?= /* @noEscape */ $block->getBreakpoints() ?>
            }
        }
    }
</script>
<script type="text/javascript">
    require(['jquery', 'owl_carousel'],
        function ($) {
            let galleryContainer = $('[data-gallery-role=gallery-placeholder]');

            if (!$('body').hasClass('page-layout-product-type-b') && galleryContainer.length > 0) {
                galleryContainer.on('gallery:loaded', function () {
                    let swatchOptions = $('.swatch-attribute-options');
                    swatchOptions.on('click', carouselDestroy);
                    $(this).on('fotorama:ready', function(){
                        let api = $(this).data('gallery'),
                            fotoramaNavGrab = $('div.fotorama__nav__shaft.fotorama__grab'),
                            fotoramaFrame = $('.fotorama__grab .fotorama__nav__frame'),
                            fotoramaWrap = $('.fotorama__nav-wrap'),
                            size = api.fotorama.size

                        carouselInit();
                        if (size > 6) {
                            fotoramaWrap.addClass('active-items');
                        } else {
                            fotoramaWrap.removeClass('active-items');
                        }

                        $(galleryContainer).on('fotorama:show',
                            function (e, fotorama, extra) {
                                let size = api.fotorama.size,
                                    currentItem = api.fotorama.activeIndex + 1;
                                if (size >= 5) fotoramaNavGrab.addClass('active-items');
                                if (currentItem == size) {
                                    fotoramaNavGrab.css('margin-left', '-' + fotoramaFrame.outerWidth() + 'px');
                                } else {
                                    fotoramaNavGrab.css('margin-left', '0');
                                }
                            }
                        )
                    });
                });
            }

            if (!$('body').hasClass('page-layout-product-type-b') && $('.product-info-media-add').length > 0) {
                galleryContainer.on('fotorama:load', function () {
                    var _height = galleryContainer.find('.fotorama__stage__frame.fotorama__active .fotorama__img').height();
                    $('.product-info-media-add').appendTo(galleryContainer);
                    $('.product-info-media-add').css({top: _height, bottom: 'auto'});
                });
            }

            if ($('body').hasClass('page-layout-product-type-b') && galleryContainer.length > 0) {
                let navBtnL = $('<span class="arrow-left">&nbsp;</span>'),
                    navBtnR = $('<span class="arrow-right">&nbsp;</span>'),
                    counter = $('<span class="counter"></span>');

                galleryContainer.on('gallery:loaded', function () {
                    let api = $(this).data('gallery');

                    galleryContainer.append(navBtnL);
                    galleryContainer.append(navBtnR);
                    galleryContainer.append(counter);

                    $(this).on('fotorama:ready', function() {
                        counter.text(api.fotorama.activeIndex + 1 + ' / ' + api.fotorama.size);
                    })
                    navBtnL.on('click', function (){
                        api.fotorama.show(api.fotorama.activeIndex - 1);
                        counter.text(api.fotorama.activeIndex + 1 + ' / ' + api.fotorama.size);
                    })
                    navBtnR.on('click', function (){
                        api.fotorama.show(api.fotorama.activeIndex + 1);
                        counter.text(api.fotorama.activeIndex + 1 + ' / ' + api.fotorama.size);
                    })
                })
            }

            function carouselInit() {

            }
            function carouselDestroy() {
                let carouselElement = $('.fotorama__nav-wrap--horizontal .fotorama__nav__shaft');
                if (carouselElement.length > 0) {
                    let owlCarouselAPI = carouselElement.data('owlCarousel');
                    if (owlCarouselAPI !== undefined) {
                        carouselElement.trigger('destroy.owl.carousel');
                    }
                }
            }
        });
</script>
