<?php
if ($block->getRatings() && $block->getRatings()->getSize()) {
    $maxSizeRating = 0;
    foreach ($block->getRatings() as $_rating) {
        $options = $_rating->getOptions();
        $iterator = count($options);
        if ($maxSizeRating < $iterator) {
            $maxSizeRating = $iterator;
        }
    }
}
?>

<div class="block review-add">
    <div class="block-content">
        <?php if ($block->getAllowWriteReviewFlag()) : ?>
            <form action="<?= $block->escapeUrl($block->getAction()) ?>" class="review-form" method="post" id="review-form" data-role="product-review-form" data-bind="scope: 'review-form'">
                <div class="block-title"><?= $block->escapeHtml(__('Write Your Own Review')) ?></div>            
                <?= $block->getBlockHtml('formkey') ?>
                <?= $block->getChildHtml('form_fields_before') ?>
                <fieldset class="fieldset review-fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                    <?php if ($block->getRatings() && $block->getRatings()->getSize()) : ?>
                        <span id="input-message-box"></span>
                        <fieldset class="field required review-field-ratings">
                            <div class="rating-title"><?= $block->escapeHtmlAttr(__('How do you rate this product?')) ?></div>
                            <div class="control">
                                <div class="nested" id="product-review-table">
                                    <table class="field choice review-field-rating">
                                        <tbody class="control review-control-vote">
                                            <tr class="review-control__head">
                                                <td>&nbsp;</td>
                                                <?php for ($iterator = 1; $iterator < $maxSizeRating + 1; $iterator++) : ?>
                                                    <td><span class="review-control__head__item"><?= $iterator; ?></span></td>
                                                <?php endfor; ?>
                                            </tr>
                                            <?php foreach ($block->getRatings() as $_rating) : ?>
                                                <?php $options = $_rating->getOptions(); ?>
                                                <tr class="review-control__items">
                                                    <td><span class="review-control__items__title"><?= $block->escapeHtml($_rating->getRatingCode()) ?></span></td>
                                                    <?php $iterator = 1;
                                                    foreach ($options as $_option) : ?>
                                                        <td>
                                                            <label for="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $block->escapeHtmlAttr($_option->getValue()) ?>">
                                                                <input type="radio" name="ratings[<?= $block->escapeHtmlAttr($_rating->getId()) ?>]" id="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $block->escapeHtmlAttr($_option->getValue()) ?>" value="<?= $block->escapeHtmlAttr($_option->getId()) ?>" class="radio" data-validate="{'rating-required':true}" aria-labelledby="<?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_rating_label <?= $block->escapeHtmlAttr($_rating->getRatingCode()) ?>_<?= $block->escapeHtmlAttr($_option->getValue()) ?>_label" />
                                                                <label>
                                                                    <?php $iterator++; ?>
                                                        </td>
                                                    <?php endforeach; ?>
                                                </tr>
                                            <?php endforeach; ?>
                                        </tbody>
                                    </table>
                                </div>
                                <input type="hidden" name="validate_rating" class="validate-rating" value="" />
                            </div>
                        </fieldset>
                    <?php endif ?>
                    <div class="field review-field-text required">
                        <label for="review_field" class="label"><span><?= $block->escapeHtml(__('Let us know your thoughts')) ?></span></label>
                        <div class="control">
                            <textarea name="detail" id="review_field" cols="5" rows="3" data-validate="{required:true}" data-bind="value: review().detail"></textarea>
                        </div>
                    </div>
                    <div class="field review-field-summary required">
                        <label for="summary_field" class="label"><span><?= $block->escapeHtml(__('Summary of Your Review')) ?></span></label>
                        <div class="control">
                            <input type="text" name="title" id="summary_field" class="input-text" data-validate="{required:true}" data-bind="value: review().title" />
                        </div>
                    </div>
                    <div class="field review-field-nickname required">
                        <label for="nickname_field" class="label"><span><?= $block->escapeHtml(__('What\'s your nickname?')) ?></span></label>
                        <div class="control">
                            <input type="text" name="nickname" id="nickname_field" class="input-text" data-validate="{required:true}" data-bind="value: nickname()" />
                        </div>
                    </div>
                </fieldset>
                <div class="actions-toolbar review-form-actions">
                    <div class="primary actions-primary">
                        <button type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Submit Review')) ?></span></button>
                    </div>
                </div>
            </form>
            <script type="text/x-magento-init">
                {
    "[data-role=product-review-form]": {
        "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
    },
    "#review-form": {
        "Magento_Review/js/error-placement": {},
        "Magento_Review/js/validate-review": {},
        "Magento_Review/js/submit-review": {}
    }
}
</script>
        <?php else : ?>
            <div class="message info notlogged" id="review-form">
                <div>
                    <?= $block->escapeHtml(__('Only registered users can write reviews. Please <a href="%1">Sign in</a> or <a href="%2">create an account</a>', $block->getLoginLink(), $block->getRegisterUrl()), ['a']) ?>
                </div>
            </div>
        <?php endif ?>
    </div>
</div>