<?php
/** @var \Magento\Review\Block\Product\Review $block */
?>
<div class="value" desktop-label="Customer Reviews">
    <div id="product-review-container" data-role="product-review"></div>
    <div class="product-reviews-summary short empty collapsible-block"  data-mage-init='{"collapsible":{"collapsible": true, "active": false, "openedState": false }}'>
        <h3 class="block-title title" role="heading"  data-role="title">
            <span class="add-review" role="heading" aria-level="2">
                <?php if ($block->getCollectionSize() < 1): ?>
                <?= $block->escapeHtml(__('Be the first to review this product')) ?>
                <?php else: ?>
                    <?= $block->escapeHtml(__('Add your review')) ?>
                <?php endif; ?>
            </span>
        </h3>
        <div class="review-form-content" data-role="content"><?= $block->getChildHtml() ?></div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Review/js/process-reviews": {
                "productReviewUrl": "<?= $block->escapeJs($block->getProductReviewUrl()) ?>",
                "reviewsTabSelector": "#tab-label-reviews"
            }
        }
    }
</script>
