<?php

use Amasty\Finder\Model\Source\DisplayType;

/**
 * @var $block \Amasty\Finder\Block\Form
 * @var Magento\Framework\Escaper $escaper
 */
?>
<div class="amfinder-common-wrapper amfinder-<?= $escaper->escapeHtml($block->getFinder()->getTemplate()); ?>
     <?= $escaper->escapeHtml($block->getHideClassName()) ? 'amfinder-hide' : ''?>"
     id="<?= 'amfinder_' . $escaper->escapeHtml((int)$block->getFinder()->getId()); ?>"
     location="<?= $escaper->escapeHtml($block->getLocation()); ?>">
    <form method="post" action="<?= $escaper->escapeUrl($block->getActionUrl()); ?>" data-mage-init='{"validation":{}}'>
        <input type="hidden" name="finder_id" value="<?= $escaper->escapeHtml($block->getId()) ?>"/>
        <input type="hidden" name="back_url" value="<?= $escaper->escapeUrl($block->getBackUrl()) ?>"/>
        <input type="hidden" name="reset_url" value="<?= $escaper->escapeUrl($block->getResetUrl()) ?>"/>
        <input type="hidden" name="category_id" value="<?= $escaper->escapeHtml($block->getCurrentCategoryId()) ?>"/>
        <input type="hidden" name="current_apply_url"
               value="<?= $escaper->escapeUrl($block->getCurrentApplyUrlEncoded()) ?>"/>
        <div class="amfinder-title" data-amfinder-js="title">
            <?= $escaper->escapeHtml($block->getFinder()->getName()) ?>
        </div>
        <ul class="amfinder-toggle">
             <?php foreach ($block->getFinder()->getDropdowns() as $dropdown) : ?>
                <li style="width: <?= $block->getDropdownWidth() ?>%" class="am-item -list-item">
                    <div class="dropdown-title <?= $dropdown->getRequired() ? 'required' : '' ?>">
                        <?= $escaper->escapeHtml(__($dropdown->getName())) ?>
                    </div>
                    <div class="dropdown-element amshopby-clearer">
                        <?php if ($dropdown->getDisplayType() == DisplayType::DROPDOWN) : ?>
                            <div class="amfinder-select-wrapper">
                                <select <?= $block->getDropdownAttributes($dropdown) ?> data-amfinder-js="select"
                                        class="amfinder-select" required="<?= $dropdown->getRequired() ?>">
                                    <?= $block->getDropdownHtml($block->getFinder(), $dropdown); ?>
                                </select>
                            </div>
                        <?php else : ?>
                            <div class="amfinder-dropdown-wrapper" data-amfinder-js="wrapper">
                                <div class="amfinder-dropdown" <?= $block->getDropdownAttributes($dropdown) ?>
                                     data-amfinder-js="select">
                                    <span data-amfinder-js="text">
                                        <?= $escaper->escapeHtml(__('Please Select ...')); ?>
                                    </span>
                                    <span class="amfinder-reset"
                                          title="<?= $escaper->escapeHtml(__('Reset option')); ?>"
                                          data-amfinder="reset"></span>
                                </div>
                                <div class="amfinder-details" data-amfinder-js="select-details">
                                    <?= $block->getDropdownHtml($block->getFinder(), $dropdown); ?>
                                </div>
                            </div>
                        <?php endif ?>
                    </div>
                </li>
            <?php endforeach ?>
            <li class="last -list-item">
                <div class="amfinder-buttons <?= ($block->isButtonsVisible() ? '' : 'no-display') ?>"
                     data-amfinder-js="buttons">
                    <button class="button" name="reset" value="1" title="<?= $escaper->escapeHtml(__('Reset')); ?>"
                            type="submit">
                        <?= $escaper->escapeHtml(__('Reset')); ?>
                    </button>
                    <button class="button action primary" title="<?= $escaper->escapeHtml(__('Find')); ?>"
                            type="submit">
                        <?= $escaper->escapeHtml(__('Find')) ?>
                    </button>
                </div>
            </li>
        </ul>
    </form>
</div>
<script type="text/javascript">
    require(['jquery', 'Amasty_Finder/js/amfinder'], function ($) {
        var finderConfig = <?= $block->getJsonConfig(); ?>;

        $("#" + finderConfig.containerId).amfinder(finderConfig);
    });
</script>
<br/>
